### ISSUE TITLE
I'm looking for someone to help with project management and maintenance

### ISSUE THREAD

**Issue by Necrophagos** [Necrophagos/SF4ComboTrainer#10]
Hi fellow contributors,

first off - thank you all for contributing to the project!
I'm always happy when I see the "new pullrequest" notification because it means one of you took the time and did some actual work. But it also means that I have to review the code, see if it works, test it and also sometimes decide if the feature is actually worth adding to the project.

By that I mean that I'm always a bit cautios when it comes to code updates that expand the feature catalog at this stage where the core software is still a bit off a mess. 

Since I'm not a master at project management and I also don't really know how to utilize github to its fullest I'm looking for someone who would assume another authority role for the main repository. Dealing with pull requests, deciding if updates belong to the master branch or would rather fit into a some sort of staging/wip branch. Reviewing and merging updates.

So if you're interested please say so.
I'd also be interested in what you would say are currently top priority tasks and what should be added to the software so we can slowly but steadily build some sort of roadmap for the project.

I'm going to link here anyone who has currently contributed to or forked the repo.

@cbcoolbox
@GreenZebra
@Ceaseless
@aefreedman
@ashstampede
@leemi
@pakoito
@shonen34
@thopiddock

edit: I'm also going to link here the major outlets where people discussed the software so you can see what feature are requested by users

http://www.reddit.com/r/SF4/comments/1uhg11/i_wrote_a_program_that_may_help_you_with_combo/
http://www.reddit.com/r/SF4/comments/1v2hjy/new_combo_trainer_version_released/
http://www.eventhubs.com/news/2014/jan/05/combo-trainer-super-street-fighter-4-arcade-edition-v2012-helps-you-learn-timing-and-which-setups-are-possible/
http://www.youtube.com/watch?v=-cgYgKf4dFY
http://shoryuken.com/2014/01/08/level-up-your-super-street-fighter-iv-arcade-edition-ver-2012-combo-execution-with-necro-phagos-pc-combo-trainer/
http://www.wired.com/gamelife/2014/01/street-fighter-combo-trainer/

**Comment by thopiddock** [comment]
I am for sure interested. I have been trying to find people to work on this sort of application with for a wee while now and I have managed to merge a lot of my input system into my fork already and I'm currently working on that.

In terms of priorities I would work on the memory class to make sure we make it as supportable as possible with players' individual settings in game. Testing with a lower end machine at home I found it can affect performance, trying to support the "Level Detail: Low" graphics settings should be a top priority for this reason. I'm not so familiar with the memory class or what memory address offsets are needed for each SF4 setting so this would need looking into by someone else - However in terms of merging it into any brand it is very easy to accommodate.

Secondly I would work on the interface a little more. The addition of the quick inputs has been insanely good as an improvement, it's much nicer than the check boxes and I think looking into this and implementing keyboard shortcuts/xbox controller support (which I am working on in my branch) will make composing these combos and timelines a lot easier.

Medium/High issue is code naming convention. I have already re-factored my branches as I work well with private members being headlessCamelCase and public members CamelCase.

Low Priority would be the recording system and demo combo files. The combo files are being made by the community quite a bit, just following reddit/r/sf4 I can see a few people saying that if we simply organised the sidebar to store these combo files that they would happily create them. The YouTube channel video also has MetalMusicMan04 helping out - so we definitely have community support on this project. Lets utilise it.

That's my view and ideas. I would be more than happy to help out with the management as I am online for the majority of my day and get a good amount of time to spend on personal projects during the day.

Tom "Xeolleth"

**Comment by cbcoolbox** [comment]
As much as i wanted to do a ton of things for this project i feel the more people that start adding things they personally want the worse the product will become.  If there was a unified idea of what this tool should be and nothing more it'd help the focus of the commits.

That being said @GreenZebra killed it on the ui, one thing i think would help change it is put the save/append/load action for the timeline in a menu. Then change the timeline to use the images on the buttons instead of saying LK LP etc.

Only other thing i think should be in this tool is having all the frame data for each character and then applying it top the buttons and visually showing that two attacks link on the timeline. This would be neat but very very time consuming.

Necrophagos did a great job getting this to be usable with some really simple and readable code, this one tool doesn't need to do everything we can think of. If we can keep it focused on what it is it could be fucking awesome (already is good enough for me).

**Comment by leemi** [comment]
I'm more of a UI guy, so my recommendations are:

A temporal timeline. Similar to how [Adobe Flash](https://wiki.brown.edu/confluence/download/attachments/4415/Flash_timeline.gif?version=1&modificationDate=1152908704000) does theirs. This would allow the user to anticipate and visualize the timing of the combo in addition to hearing it.

We shouldn't need to create any more demo combo files. If we make the editing process as painless as possible, the community will make them for us.

One of the major annoyances for me is figuring out the approximate number of frames between each input. Which is why I feel that a basic recording system would really help. Even if it takes inputs from just the keyboard (timing everything at 1/60, it would provide a starting point for figuring out the exact number of frames. I had the same idea as @cbcoolbox with the frame data, but haven't been able to find a computer-readable source of frame data.

On a side note, my submissions show up as @GreenZebra, I'm not sure why.

**Comment by cbcoolbox** [comment]
Sorry, then @leemi killed it on the ui.

Also Necrophagos already sent me one, if you want me to email it to you.

**Comment by sweetclimusic** [comment]
Think i will comment on my current project.  I am generalizing the project so that this app can work on any 2d game that you know the memory address for. Since this is based of of sf4 showoff which has located the mem address for KOF and i dont play sf4. I am hoping to have a branch where a user can switch on the fly to the various trainer based on the game they are playing. 

I was simply copy/paste/edit at first but anytime i have code that is exactly the same somewhere else i want to encapsulate it. I had a launcher form that started the various game form you wanted to train on but I am currently working on a serialize game object from a xml file. so all the games the user/ the app knows about is generated on the launch form and in app menuitem to switch to xTrainer. This is still using the concept of fix memory address which if there is an overall issue you could specify the the low detail is X offset in the xml file and in the add a option to shift to low detail address. I know the original SF4 showoff author used cheat engine to find the address that are currently know, but i have no knowledge of that software. 

far as github, this is my first project and usage of git i couldn't get the updated files from the master that changed after i forked it. I have found a guide and its odd that you have more control or rather a understandable work flow from the command tool than the gui. 

after which I was also hoping to add drag and drop to the timeline to move parts of the combo around. 

I agreed a coding standard for this project needs to be the first thing. i use variable names are lowerUpper and method name are Upper, any property, variable or method used/found globally starts with a _ and then follows my previous 2 rules

I'm please this project exist as it was something i had wanted to do but was put off by the idea of overloading the directx buffer as i wanted a ' music' sheet timeline to be displayed over the actual game so a future/would be nice is the temporal time line.

I had a question,why isnt the FPS.cs class used? would addressing the memory/low machine spec issue be address by the app have its on 'game loop' that is currently timing our inputs with the sound every 1/60 not be the approach?

**Comment by thopiddock** [comment]
@leemi / @GreenZebra ? / @cbcoolbox  I funnily enough have been working on frame data for characters and putting into a decent format as an aim for a separate project. I can import that into this project pretty easily later down the line. XML looks like this:

```
<Character Name="Ryu" Type="Shoto">
  <Description>
    He likes fireballs.
  </Description>
  <Statistics
    HealthPoints="1000"
    StunPoints="1000"
    ForwardSpeed="0.045"
    BackwardSpeed="0.030"
    />
  <Moves>
    <Move Id='1' Name='Close Jab' Input='Close Jab' Notation='LP' Notes=''>
      <Hit High='TRUE' Low='TRUE' Damage='30' Stun='50' Gain='20' CancelAbility='ch/sp/su'
          Startup='3' Active='3' Recovery='6' OnGuard='2' OnHit='5' />
    </Move>
  <Move Id='6' Name='Close Roundhouse' Input='Close Roundhouse' Notation='HK'  Notes=''>
      <Hit High='TRUE' Low='TRUE' Damage='40' Stun='125' Gain='60' CancelAbility='su*'
            Startup='8' Active='8' Recovery='2' OnGuard='-1' OnHit='4'/>
      <Hit High='TRUE' Low='TRUE' Damage='70' Stun='75' Gain='20' CancelAbility='su*'
      Startup='8' Active='4' Recovery='15' OnGuard='-1' OnHit='4'/>
  </Move>
 </Moves>
</Character>
```

This should let us do those suggestions - the only thing is actually getting this data is hard work and takes a long time to write out (I did Ryu's full set manually... :| )

**Comment by leemi** [comment]
@cbcoolbox The data unfortunately doesn't include special, super or ultra moves.
@thopiddock, That looks like so much work. I'm excited for when it is completed!

**Comment by cbcoolbox** [comment]
Those would be extremely easy to add, it's obviously not complete but it's a damn good start. Like we've all said it would be awesome but so much work.

**Comment by Necrophagos** [comment]
hey this sparked a discussion. nice!
ty all for your input.

Ok first thing

>  i feel the more people that start adding things they personally want the worse the product will become.

is a sentiment I totally agree but didn't have the courage to say so bluntly.
yes I do want to keep the application neat and simple. or at least look like it. personally I have only three goals: 1. clean code 2. better timeline ui 3. awesome performance. in that order... but... since this has become a community effort and also because sometimes I don't see the potential in rough things I'm very open to the new ideas!

still I think in some case you have to hold back your enthusiam a little to let the core product evolve.

with that said I want to accept your offer to help with management @thopiddock 
First thing you'll have to do is probably integrate your own pull request that has been standing open for the last couple of days ;/ 

Second thing
Do you all have write privileges on the wiki?
https://github.com/Necrophagos/SF4ComboTrainer/wiki/Roadmap

I will redo some readme and wiki stuff in the coming time. I'll try to create a concise roadmap also integrating the ideas you have mentioned in this thread/issue.

Third thing
Opening this issue did work really good, but how is discussion supposed to work here on github. Is this the way? Seems a little weird. 
Still I'm very happy you guys responded because you worded some thoughts right out of my head. Communication is king.

**Comment by thopiddock** [comment]
@cbcoolbox @leemi @Necrophagos  I'm more than willing to put in the work. Like I said - I was going to do this app anyway to show all the possible link, chain and cancel combinations of moves on a character. I can incorporate it into the app once we have the core completed and (more importantly) working _robustly_.

@Necrophagos  With regards to github the best way to build a roadmap is by making issue posts as specific as possible:

> **Button Graphics need updating** - Update icons to be colour blind friendly
> 
> **Create Timeline "Timeline"** - Create a no concise and clear timeline 
> 
> **Display a timeline overlay in game** - Customisable timeline overlay to go in game. Plays when the first PressInput has been made.

Simple tasks then can spur discussion (much like this post did) from that you can judge the next issue(feature) branch you wish to work on next and generally get a good work flow going.

The Wiki would be a good thing to keep up to date with actual _implemented_ features. Much like any Wiki page it just needs to be simple and to the point - just make it into a guide for users. I feel a mistake often made is using it for dev notes instead of keeping that wrapped up in the issue tracker which is designed for that task.

I'll clean up my changes for the Recording branch and see if I can sort out the pull request. I did get the permissions for the Roadmap as well so it updated fine.

**Comment by thopiddock** [comment]
@Necrophagos - this is quite a large branch update now - @cbcoolbox  @leemi  - this branch I'm going to pull in has separated the logic (as much humanly possible) from the main project and into a Model project. This means we can work on the UI in Winforms AND in WPF and see what improvements we can make in either. It also means we isolate the code logic that handles working directly with SSF4.exe which is important if we are going to keep the performance smooth.
