### ISSUE TITLE
License file/info missing from repository

### ISSUE THREAD

**Issue by DangerOnTheRanger** [Necrophagos/SF4ComboTrainer#11]
Just thought I'd mention the fact that the code as it is is unlicensed, and unfortunately due to the way copyright works is not technically open-source. Not sure if that was your intention, but since it's on GitHub and all, I assume you didn't mean to do that.

**Comment by thopiddock** [comment]
This is a very good point. We'll get onto that right away. @Necrophagos - what license would you like to apply to the project (let us not forget any other references or snippets used either).

**Comment by Necrophagos** [comment]
yeah licensing, what a boring topic. but I guess there's no way around it.

I'd probably vote for the MIT License because its very simple. The only problem is the code parts that I intentionally stole from lullius's sf4-show-off-project (v.0.5) and that is the address information inside sf4memory.cs.
I don't know what to do with this, I'm not very proud of it, but I would do it again.

the other things are the InputSimulator library which is a microsoft product
and the memoryeditor library which is from somewhere else I don't know where
the last thing are the button images from a user namend blendmaster from strategy wiki.

I guess we need some kind of license and then specifically exlude certain files from that license.

what do you think?

**Comment by thopiddock** [comment]
I believe an MIT or GPL would be fine but I like to idea of keeping this open source along it's life time and tend to use http://www.mozilla.org/MPL/2.0/ on my open source projects.

It also means any software we have used cannot be used commercially and sold which covers the software snippets we have used.

If we have the InputSimulator then we will just include the original MS-PL license that I found in the developers notes. Using it for free and in conjunction with a copyleft style of license, we should not have to worry about anything further.

Shall I put the InputSimulator MS-PL license and the MPLv2.0 license in the next commit?

**Comment by Necrophagos** [comment]
afair none of the major open source licenses forbid comercial use. http://choosealicense.com/licenses/

I'm fine with the MPL though.

**Comment by DangerOnTheRanger** [comment]
Any particular reason you're thinking about using the MPL?

**Comment by Necrophagos** [comment]
because it enforces open source but is a little more permissve compared to GPL, what do you have in mind?

**Comment by DangerOnTheRanger** [comment]
I think it should be noted that it is impossible for an open-source license to forbid commercial distribution. [It wouldn't  be an open-source license otherwise.](http://opensource.org/osd)

 I don't have any problem with the MPL - I was just curious as to why you were using it. As far as I can tell from reading the license, it is almost identical to the LGPL:
- Extra code in separate files can be licensed however the creator of that code pleases. The LGPL requires that that extra code must dynamically link with your own code to be licensed like that, whereas the MPL has no such restriction.
- The LGPL allows modifications to code licensed under the LGPL to be licensed under the GPL instead if the creator of those modifications would prefer that. According to my understanding of the MPL (I am _not_ a lawyer), it does not allow this.
- The MPL allows dual-licensing of software covered by the MPL under the GPL, LGPL, and the AGPL unless the creator of the MPL'ed software explicitly forbids this - see sections 1.5 and 3.3 and Exhibit B in the MPL for more on that. According to my understanding - again, I am not a lawyer - you can only allow _all_ of the aforementioned GPL variants to be a valid dual-license choice or none at all, i.e, no picking and choosing.

I'm not against the MPL - I think it's a great choice, in fact - I was just making sure you're aware of what specifically it allows that the GPL does not.

**Comment by Necrophagos** [comment]
afaik, the LGPL is more common to use with libarys especially if they want to stay open source but want to allow to be used within non-open-source products. maybe I'm wrong.

But this software isn't a library and I guess MPL is cool and I also hate this lawerism because honestly I don't understand it fully.

Thx @DangerOnTheRanger for bringing it up though!
